title: Inês Esteves
email: inesaesteves0@gmail.com
behance: inesteves
linkedin_username: inesaesteves
github_username: estevesi
description: Hi! My name is Inês, I'm a digital product designer and this is my portfolio!
baseurl: "/projeto" 
url: "" 

collections:
  work:
    output: true
    permalink: /work/:path

permalink: /:categories/:year/:title:output_ext

theme: minima
plugins:
  - jekyll-feed
